### ISSUE TITLE
Usage test not running correctly

### ISSUE THREAD

**Issue by eriknes** [tjefferies/pymetalog#14]
Trying to run the example script, but PyMetalog_usagetest is not running as expected:

1. First error message:

TypeError: __init__() got an unexpected keyword argument 'save_data'

2. Second error message after removing the save_data parameter

'numpy.ndarray' object has no attribute 'values'

Would be nice if this was working correctly

**Comment by i001962** [comment]
Same error here. Commenting to bump maintainers for hints. I'm trying with py3.8. @eriknes did you ever get unstuck?

**Comment by hrenski** [comment]
I had the same problem as well while running some tests... looked into the code... 

1. The main class ```metalog``` does not have a save_data parameter in the constructor. I'm guessing this was in a previous version but was removed (?). You can just remove that parameter in the test script when creating an instance of the ```metalog``` class.

2. For me, the problem was coming from line 215 in the file ```a_vector.py```; specifically, in the call ```m_dict['dataValues']['z'].values``` within the ```np.repeat```.  Did a little poking around with some print statements, and it looks like ```m_dict['dataValues']``` is a dictionary (within the ```m_dict``` dictionary) which holds an numpy array (which does not have a values attribute as the error indicates). Changing ```m_dict['dataValues']['z'].values``` to ```m_dict['dataValues']['z']``` allowwed the code to pass through. To be clear, line 215 should now read: 
```Z = np.column_stack((np.array(m_dict['dataValues']['z']),np.repeat(m_dict['dataValues']['z'].values,ncols-1).reshape(len(m_dict['dataValues']['z']),ncols-1)))```

This let me continue with my tests...

Hope this helps!

**Comment by tjefferies** [comment]
Closed by #17
